config/routes.rb
Rails.application.routes.draw do
  root "departments#index"
  
  resources :departments do 
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  
  def index
    @departments = Department.all
  end

  def show
  end

  def new
    @department = Department.new
    render partial: "form"
  end
  
  def edit
    render partial: "form"
  end

  def create
    @department = Department.new(department_params)
    if @department.save
      redirect_to departments_path
    else
      render :new
    end
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private
    def department_params
      params.require(:department).permit(:name)
    end

    def set_department
      @department = Department.find(params[:id])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_department
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to @item
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :available)
  end

  def items_department
    @item = item.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1><%= @department.id ? 'Edit Department' : 'Create Department' %></h1>
<hr />
<%= form_for @department do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/departments/edit.html.erb
<h1>Edit Department: <%= department.name %></h1>
<%= render 'form'%>

app/views/departments/index.html.erb
<h1>Show all departments</h1>
<%= link_to 'Create new department', new_department_path %>
<ul>
  <% @departments.each do |department| %>
    <li>
    <%= link_to department.name, department %>
    </li>
  <% end %>
</ul>

app/views/departments/new.html.erb
<h1>Departments#new</h1>
<p>Find me in app/views/departments/new.html.erb</p>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'Back', departments_path %>
<br />
<%= link_to 'Edit department name', edit_department_path(@department) %>
<br />
<%= link_to 'Delete department', @department, method: :delete %>
<br />

app/views/items/_form.html.erb
<h1><%= @item.id ? ' Edit Item ' : 'Create Item' %></h1>
<hr />
<%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>

<%= f.label :name %>
<%= f.text_field :price %>

<%= f.label :name %>
<%= f.select :available %>

  <%= f.submit %>
<% end %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items</h1>
bundle

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>